version: 2.1

executors:
  linux:
    docker:
      - image: ethereum/cpp-build-env:11
  linux-gcc-9:
    docker:
      - image: ethereum/cpp-build-env:12-gcc-9
  linux-gcc-7:
    docker:
      - image: ethereum/cpp-build-env:12-gcc-7
  linux-clang-9:
    docker:
      - image: ethereum/cpp-build-env:12-clang-9
  macos:
    macos:
      xcode: 11.1.0

commands:
  build:
    description: "Build"
    steps:
      - checkout
      - run:
          name: "Update submodules"
          command: git submodule update --init --recursive
      - run:
          name: "Environment"
          command: |
            CC=${CC:-cc}
            CXX=${CXX:-cpp}
            echo CC: $CC
            echo CXX: $CXX
            $CC --version
            $CXX --version
            cmake --version

            # Create the toolchain.info file for cache key.
            echo $TOOLCHAIN >> toolchain.info
            $CXX --version >> toolchain.info
      - restore_cache:
          name: "Restore Hunter cache"
          key: &hunter-cache-key hunter-{{arch}}-{{checksum "toolchain.info"}}-{{checksum "cmake/Hunter/init.cmake"}}
      - run:
          name: "Configure"
          working_directory: ~/build
          command: |
            if [ "$TOOLCHAIN" ]; then
              export toolchain_option="-DTOOLCHAIN=$TOOLCHAIN"
            fi
            cmake ../project $toolchain_option -DCMAKE_INSTALL_PREFIX=~/install -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DEVMONE_TESTING=ON $CMAKE_OPTIONS
      - save_cache:
          name: "Save Hunter cache"
          key: *hunter-cache-key
          paths:
            - ~/.hunter/_Base/Cache
      - run:
          name: "Build"
          command: cmake --build ~/build -- -j4
      - run:
          name: "Install"
          command: cmake --build ~/build --target install

  test:
    description: "Test"
    steps:
    - run:
        name: "Test"
        working_directory: ~/build
        command: ctest -R ${TESTS_FILTER:-'.*'} -j4 --schedule-random --output-on-failure

  package:
    description: "Make package"
    steps:
      - run:
          name: "Build Package"
          working_directory: ~/package
          command: cmake --build ~/build --target package && mv ~/build/evmone*.tar.gz* .
      - store_artifacts:
          path: ~/package
          destination: package
      - persist_to_workspace:
          root: ~/package
          paths:
            - evmone-*

jobs:

  lint:
    docker:
    - image: ethereum/cpp-build-env:11
    steps:
    - checkout
    - run:
        name: "Check code format"
        command: |
          clang-format --version
          find include lib test -name '*.hpp' -o -name '*.cpp' -o -name '*.h' -o -name '*.c' | xargs clang-format -i
          git diff --color --exit-code
    - run:
        name: "Run codespell"
        command: |
          codespell --quiet-level=4

  release-linux:
    executor: linux-gcc-9
    environment:
      BUILD_TYPE: Release
    steps:
      - build
      - test
      - package

  release-macos:
    executor: macos
    environment:
      BUILD_TYPE: Release
    steps:
      - run:
          name: "Install System Dependencies"
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake
      - build
      - test
      - package

  deploy:
    docker:
      - image: circleci/golang
    steps:
      - run:
          name: "Install GHR"
          command: |
            GO111MODULE=on go get github.com/tcnksm/ghr@v0.12.1
      - attach_workspace:
          at: ~/package
      - run:
          name: "Create GitHub release"
          command: |
            ls -l ~/package
            prerelease_flag=$([[ $CIRCLE_TAG =~ ^v[0-9\.]+$ ]] || echo '-prerelease')
            name="$CIRCLE_PROJECT_REPONAME ${CIRCLE_TAG:1}"
            echo $name
            ghr -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -n "$name" $prerelease_flag $CIRCLE_TAG ~/package

  state-tests:
    environment:
      TESTS_REV: develop
      ALETH_REV: 1.8.0
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/package
      - run:
          name: "Unpack evmone"
          background: true
          command: tar xz < ~/package/evmone*.tar.gz
      - run:
          name: "Download Aleth"
          background: true
          command: curl -L https://github.com/ethereum/aleth/releases/download/v$ALETH_REV/aleth-$ALETH_REV-linux-x86_64.tar.gz | tar xz
      - run:
          name: "Download tests"
          command: git clone --depth=1 --single-branch --branch $TESTS_REV https://github.com/ethereum/tests
      - run:
          name: "Run State Tests"
          command: bin/testeth -t GeneralStateTests -- --testpath tests --vm lib/libevmone.so


  gcc-min:
    executor: linux-gcc-7
    steps:
      - build
      - test

  gcc-latest-coverage:
    executor: linux-gcc-9
    environment:
      BUILD_TYPE: Coverage
    steps:
      - build
      - run:
          name: "Run unit tests"
          working_directory: ~/build
          command: |
            bin/evmone-unittests
      - run:
          name: "Upload coverage data"
          command: |
            codecov --gcov-root ~/build

  gcc-32bit:
    executor: linux-gcc-9
    environment:
      TOOLCHAIN: cxx17-32bit
    steps:
      - run:
          name: "Install GCC 32-bit"
          command: |
            sudo apt -q update && sudo apt -qy install g++-multilib
      - build
      - test

  clang-latest-ubsan:
    executor: linux-clang-9
    environment:
      CMAKE_OPTIONS: -DSANITIZE=undefined,implicit-conversion,nullability
      UBSAN_OPTIONS: halt_on_error=1
      # TODO: There is unresolved __ubsan_vptr_type_cache in evmone.so
      TESTS_FILTER: unittests
    steps:
      - build
      - test

  clang-latest-coverage:
    executor: linux-clang-9
    environment:
      BUILD_TYPE: Coverage
      TESTS_FILTER: unittests
    steps:
      - build
      - run:
          name: "Run unit tests"
          working_directory: ~/build
          command: |
            bin/evmone-unittests
      - run:
          name: "Coverage report"
          working_directory: ~/build
          command: |
            mkdir ~/coverage
            llvm-profdata merge *.profraw -o evmone.profdata
            llvm-cov show lib/libevmone.so bin/evmone-unittests -Xdemangler llvm-cxxfilt -instr-profile=evmone.profdata -ignore-filename-regex=include/evmc -region-coverage-lt=100 -format=html > ~/coverage/missing.html
            llvm-cov show lib/libevmone.so bin/evmone-unittests -Xdemangler llvm-cxxfilt -instr-profile=evmone.profdata -ignore-filename-regex=include/evmc -format=html > ~/coverage/full.html

            llvm-cov report lib/libevmone.so bin/evmone-unittests -Xdemangler llvm-cxxfilt -instr-profile=evmone.profdata -ignore-filename-regex=include/evmc > ~/coverage/report.txt
            llvm-cov report lib/libevmone.so bin/evmone-unittests -Xdemangler llvm-cxxfilt -instr-profile=evmone.profdata -ignore-filename-regex=include/evmc -use-color
      - store_artifacts:
          path: ~/coverage
          destination: coverage



  macos-asan:
    executor: macos
    environment:
      BUILD_TYPE: RelWithDebInfo
      CMAKE_OPTIONS: -DSANITIZE=address
      TESTS_FILTER: unittests
    steps:
      - run:
          name: "Install System Dependencies"
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake
      - build
      - test

workflows:
  version: 2
  evmone:
    jobs:
      - lint
      - release-linux:
          filters:
            tags:
              only: /.*/
      - release-macos:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - release-linux
            - release-macos
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9].*/
      - state-tests:
          requires:
            - release-linux
      - gcc-min
      - gcc-latest-coverage
      - clang-latest-ubsan
      - clang-latest-coverage
      - macos-asan
      - gcc-32bit
